image:
  repository: ghcr.io/netbootxyz/netbootxyz
  pullPolicy: IfNotPresent
  tag: 0.6.6-nbxyz10@sha256:4fff0c570ba97c1640ab86e61111920505389c0f42e2645b0ff4d4b3e742e594

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env: {}

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10161
  tftp:
    ports:
      tftp:
        targetport: 69
        port: 69
        protocol: UDP
  assets:
    ports:
      assets:
        targetport: 8080
        port: 10162

persistence:
  config:
    enabled: true
    mountPath: "/config"
  assets:
    enabled: true
    mountPath: "/assets"
