image:
  repository: nginxinc/nginx-unprivileged
  pullPolicy: IfNotPresent
  tag: 1.20.2-alpine-amd64

env:
  PUID: 568
  PGID: "{{ .Values.env.PUID }}"

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10162

persistence:
  config:
    enabled: true
    mountPath: "/etc/nginx/"
  html:
    enabled: true
    mountPath: "/usr/share/nginx/htm"
