image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: 1.20.2-alpine

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  {}

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10162

persistence:
  config:
    enabled: true
    mountPath: "/etc/nginx/"
  html:
    enabled: true
    mountPath: "/usr/share/nginx/html"
